# Site settings
title: "Sophie Ramsden"
#email: contact@sophieramsden.ca
#description: ""
#url: "http://nadineramsden.ca" # the base hostname & protocol
github_username: sophieramsden
#logo: /images/logo/ram_logo.png
# Build settings
markdown: kramdown
theme: Slate
# gems:
#   - jekyll-redirect-from
#   - jekyll-sitemap
#   - jekyll-seo-tag
#   - jekyll-paginate
#   - jekyll-gist

# exclude:
